export const coreBlocks: string[] = [
  // Text blocks
  'core/paragraph',
  'core/heading',
  'core/list',
  'core/list-item',
  'core/quote',
  'core/code',
  'core/preformatted',
  'core/verse',
  'core/pullquote',
  'core/classic',

  // Media blocks
  'core/image',
  'core/gallery',
  'core/audio',
  'core/video',
  'core/file',
  'core/media-text',
  'core/cover',

  // Design blocks
  'core/group',
  'core/columns',
  'core/column',
  'core/row',
  'core/stack',
  'core/grid',
  'core/buttons',
  'core/button',
  'core/separator',
  'core/spacer',
  'core/page-break',

  // Theme blocks
  'core/site-title',
  'core/site-tagline',
  'core/site-logo',
  'core/navigation',
  'core/navigation-link',
  'core/navigation-submenu',
  'core/query',
  'core/query-loop',
  'core/query-pagination',
  'core/query-pagination-next',
  'core/query-pagination-previous',
  'core/query-pagination-numbers',
  'core/query-no-results',
  'core/query-title',
  'core/post-title',
  'core/post-content',
  'core/post-date',
  'core/post-excerpt',
  'core/post-featured-image',
  'core/post-author',
  'core/post-author-name',
  'core/post-author-biography',
  'core/post-terms',
  'core/post-navigation-link',
  'core/post-comments-count',
  'core/post-comments-link',
  'core/post-comment',
  'core/post-comment-author',
  'core/post-comment-date',
  'core/post-comment-content',
  'core/post-comments-form',
  'core/post-template',
  'core/term-description',
  'core/archive-title',
  'core/categories',
  'core/tag-cloud',
  'core/search',
  'core/calendar',
  'core/rss',
  'core/social-links',
  'core/social-link',
  'core/shortcode',
  'core/archives',
  'core/loginout',
  'core/page-list',
  'core/page-list-item',
  'core/home-link',
  'core/template-part',
  'core/pattern',

  // Widget blocks
  'core/latest-posts',
  'core/latest-comments',

  // Interactive & embed blocks
  'core/details',
  'core/footnotes',
  'core/read-more',
  'core/comment-template',
  'core/comments',
  'core/comments-title',
  'core/comments-pagination',
  'core/comments-pagination-next',
  'core/comments-pagination-previous',
  'core/comments-pagination-numbers',
  'core/avatar',
  'core/table',
  'core/table-of-contents',
  'core/embed',
]
